version: "3"

services:
  web:
    build: ./vristo-angular-main/
    expose:
      - 80   
    ports:
      - 8081:80
    restart: always

  backend:
    build: ./backend/
    restart: always
    ports:
      - "4000:4000"
  
  mongo:
    image: mongo
    container_name: shopit
    restart: unless-stopped
    env_file: ./backend/config/config.env
    volumes:
      - ~/data/db:/data/db
    ports:
      - 27017:27017
    
